#
# Mocha configuration options can be defined in this file
#

search_dirs: "Mocha"
pages_dir: "pages"
site_url: "localhost:5000"
site_title: "Default Mocha Build"
build_dir: "site"
assets_dir: "assets"
